### ISSUE TITLE
When i import scss file i catch error

### ISSUE THREAD

**Issue by sergamers** [amercier/karma-scss-preprocessor#68]
Karma error - File to import not found or unreadable: ~styles/fonts.
Doesn't Karma know tilda? How to fix?

Angular cli 6
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-scss-preprocessor')
    ],
    files: [
      { pattern: './src/styles.scss', watched: true,  included: true, served: true }
    ],
    preprocessors: {
      '**/*.scss': ['scss']
    },
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'), reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by ashnewport** [comment]
As per a comment here [How to configure Karma to include global scss files for an angular-cli project?
](https://stackoverflow.com/questions/44460733/how-to-configure-karma-to-include-global-scss-files-for-an-angular-cli-project/44498689#44498689) you might need to install `node-sass-tilde-importer`. Info about that is at https://www.npmjs.com/package/node-sass-tilde-importer

Give it a try and see how it goes.

**Comment by victornoel** [comment]
~~@ashnewport how do you tell `karma-scss-preprocessor` to use it?~~

Here is how it works, add this to karma config:
```
    scssPreprocessor: {
      options: {
        importer: require('node-sass-tilde-importer')
      }
    }
```

Thanks @ashnewport

**Comment by victornoel** [comment]
@amercier is this closed because `node-sass-tilde-importer` is not needed anymore or because this is the recommended way of handling this problem?

**Comment by amercier** [comment]
@victornoel Sorry for closing the issue without commenting.

I think this problem is out of the scope of `karma-scss-preprocessor`. Tilde-imports are not part of the [official Sass specs](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#import), but have been introduced by Webpack's `sass-loader` ([docs](https://github.com/webpack-contrib/sass-loader#imports)). Plus, `node-sass` doesn't support tilde-import natively, and `karma-scss-preprocessor` is just a bridge between Karma and `node-sass`.

However, `node-sass` provides the `importer` option as you described, and `karma-scss-preprocessor` allows passing options to `node-sass` via the `scssPreprocessor.options` field. **So feel free to use it to enable support for tilde-imports.**

**Comment by victornoel** [comment]
@amercier thanks a lot for the explanation :)
